# Generated by Django 5.1.3 on 2024-11-21 13:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_logicleagueuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logicleagueuser',
            managers=[
                ('Mangaer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='logicleagueuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
