# Generated by Django 5.1.3 on 2024-11-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_logicleagueuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logicleagueuser',
            managers=[
            ],
        ),
    ]
