# Generated by Django 5.1.3 on 2025-03-12 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('challengeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challengeName', models.CharField(max_length=200)),
                ('challengeDesc', models.TextField(null=True)),
                ('problemStatement', models.TextField()),
                ('inputFormat', models.TextField(null=True)),
                ('outputFormat', models.TextField(null=True)),
                ('constraints', models.TextField(null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('challengeLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('isPublic', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('code', models.TextField(default='', null=True)),
                ('submission_date_time', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.FloatField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('testCaseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.JSONField(default=dict)),
                ('input_txt', models.TextField(default='')),
                ('output', models.TextField(default='')),
                ('output_txt', models.TextField(default='')),
                ('explaination', models.TextField(default='', null=True)),
                ('isSample', models.BooleanField(default=True)),
                ('marks', models.SmallIntegerField(default=0)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
            ],
        ),
    ]
