# Generated by Django 5.1.3 on 2024-11-24 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('challengeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('inputformat', models.TextField(null=True)),
                ('outputformat', models.TextField(null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('isPublic', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
