# Generated by Django 5.1.3 on 2024-12-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='description',
            new_name='challengeDesc',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='level',
            new_name='challengeLevel',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='name',
            new_name='challengeName',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='inputformat',
            new_name='constraints',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='outputformat',
            new_name='inputFormat',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='title',
            new_name='problemStatement',
        ),
        migrations.AddField(
            model_name='challenges',
            name='outputFormat',
            field=models.TextField(null=True),
        ),
    ]
