# Generated by Django 5.1.3 on 2024-11-26 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('code', models.TextField(default='', null=True)),
                ('runtime', models.CharField(null=True)),
                ('space', models.CharField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
                ('submitedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('testCaseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('desc', models.TextField(null=True)),
                ('ishiden', models.BooleanField(default=True)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
            ],
        ),
    ]
