# Generated by Django 5.1.3 on 2024-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_description_challenges_challengedesc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='ishiden',
            new_name='isSample',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output',
        ),
        migrations.AddField(
            model_name='testcase',
            name='explaination',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_txt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='marks',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_txt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='values',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='variables',
            field=models.TextField(default=''),
        ),
    ]
