# Generated by Django 5.1.3 on 2024-12-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_ishiden_testcase_issample_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='values',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='variables',
        ),
        migrations.AddField(
            model_name='testcase',
            name='input',
            field=models.JSONField(default=dict),
        ),
    ]
