# Generated by Django 5.1.3 on 2025-01-12 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_values_testcase_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='submitedBy',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='space',
        ),
        migrations.AddField(
            model_name='solution',
            name='submission_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
