# Generated by Django 5.1.3 on 2025-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_submitedby_solution_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='runtime',
            field=models.FloatField(null=True),
        ),
    ]
