# Generated by Django 5.1.3 on 2025-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring',
            field=models.TextField(blank=True, null=True),
        ),
    ]
