# Generated by Django 5.1.3 on 2025-01-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_contest_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
    ]
